-- pg_tin 0.1.0 -> 0.2.0. Generated by scripts/upgrade-sql.py from the 0.2.0
-- install script; idempotent, so it also upgrades early development builds of
-- 0.1.0. Run through ALTER EXTENSION pg_tin UPDATE.

CREATE OR REPLACE FUNCTION "tin_flush"(
	"index" oid /* pg_sys :: Oid */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_flush_wrapper';

CREATE OR REPLACE FUNCTION "tin_highlight"(
	"doc" TEXT, /* & str */
	"query" TEXT, /* & str */
	"start" TEXT DEFAULT '<b>', /* & str */
	"stop" TEXT DEFAULT '</b>' /* & str */
) RETURNS TEXT /* String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_highlight_wrapper';

CREATE OR REPLACE FUNCTION "tin_match_support"(
	"req" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_match_support_wrapper';

CREATE OR REPLACE FUNCTION "tin_match"(
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE SUPPORT "tin_match_support" COST 10
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_match_wrapper';

CREATE OR REPLACE FUNCTION tin_restrict(internal, oid, internal, integer) RETURNS float8
    STABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'tin_restrict_wrapper';

CREATE OR REPLACE FUNCTION "tin_score_inspect"(
	"index" oid, /* pg_sys :: Oid */
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS jsonb /* pgrx :: JsonB */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_score_inspect_wrapper';

CREATE OR REPLACE FUNCTION "tin_score_support"(
	"req" internal /* Internal */
) RETURNS internal /* Internal */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_score_support_wrapper';

CREATE OR REPLACE FUNCTION "tin_score"(
	"index" oid, /* pg_sys :: Oid */
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS double precision /* f64 */
STRICT STABLE PARALLEL SAFE SUPPORT "tin_score_support" COST 20
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_score_wrapper';

CREATE OR REPLACE FUNCTION "tin_search_distance"(
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS double precision /* f64 */
STRICT STABLE PARALLEL SAFE COST 10
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_search_distance_wrapper';

CREATE OR REPLACE FUNCTION "tin_search_match"(
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS bool /* bool */
STRICT STABLE PARALLEL SAFE COST 10
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_search_match_wrapper';

DROP FUNCTION IF EXISTS tin_segments(oid);
CREATE OR REPLACE FUNCTION "tin_segments"(
	"index" oid /* pg_sys :: Oid */
) RETURNS TABLE (
	"segment" INT,  /* i32 */
	"first_block" bigint,  /* i64 */
	"blocks" bigint,  /* i64 */
	"bytes" bigint,  /* i64 */
	"live_tuples" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_segments_wrapper';

DROP FUNCTION IF EXISTS tin_shared_stats();
CREATE OR REPLACE FUNCTION "tin_shared_stats"() RETURNS TABLE (
	"segments" bigint,  /* i64 */
	"bytes" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_shared_stats_wrapper';

CREATE OR REPLACE FUNCTION "tin_snippet"(
	"doc" TEXT, /* & str */
	"query" TEXT, /* & str */
	"words" INT DEFAULT 30, /* i32 */
	"start" TEXT DEFAULT '<b>', /* & str */
	"stop" TEXT DEFAULT '</b>' /* & str */
) RETURNS TEXT /* String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_snippet_wrapper';

DROP FUNCTION IF EXISTS tin_stats(oid);
CREATE OR REPLACE FUNCTION "tin_stats"(
	"index" oid /* pg_sys :: Oid */
) RETURNS TABLE (
	"segments" INT,  /* i32 */
	"live_tuples" bigint,  /* i64 */
	"pending_tuples" bigint,  /* i64 */
	"pending_bytes" bigint,  /* i64 */
	"generation" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_stats_wrapper';

ALTER OPERATOR ==> (text, text) SET (RESTRICT = tin_restrict, JOIN = contjoinsel);

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_operator WHERE oprname = '~>'
                 AND oprleft = 'text'::regtype AND oprright = 'text'::regtype) THEN
    CREATE OPERATOR ~> (
        LEFTARG = text,
        RIGHTARG = text,
        FUNCTION = tin_search_match,
        RESTRICT = tin_restrict,
        JOIN = contjoinsel
    );
  END IF;
END $$;

COMMENT ON OPERATOR ~> (text, text) IS 'search-box match: exact, prefix, fragment or typo';

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_operator WHERE oprname = '<~>'
                 AND oprleft = 'text'::regtype AND oprright = 'text'::regtype) THEN
    CREATE OPERATOR <~> (
        LEFTARG = text,
        RIGHTARG = text,
        FUNCTION = tin_search_distance
    );
  END IF;
END $$;

COMMENT ON OPERATOR <~> (text, text) IS 'search-box rank: 0 exact, 1 prefix, 2 fragment, 3-4 typos';

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_amop o JOIN pg_opfamily f ON f.oid = o.amopfamily
                 WHERE f.opfname = 'text_tin_ops' AND o.amopstrategy = 1) THEN
    ALTER OPERATOR FAMILY text_tin_ops USING tin ADD OPERATOR 1 ==> (text, text);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_amop o JOIN pg_opfamily f ON f.oid = o.amopfamily
                 WHERE f.opfname = 'text_tin_ops' AND o.amopstrategy = 2) THEN
    ALTER OPERATOR FAMILY text_tin_ops USING tin ADD OPERATOR 2 ~> (text, text);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_amop o JOIN pg_opfamily f ON f.oid = o.amopfamily
                 WHERE f.opfname = 'text_tin_ops' AND o.amopstrategy = 3) THEN
    ALTER OPERATOR FAMILY text_tin_ops USING tin ADD OPERATOR 3 <~> (text, text) FOR ORDER BY float_ops;
  END IF;
END $$;

