/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:261
-- pg_tin::tin_flush
CREATE  FUNCTION "tin_flush"(
	"index" oid /* pg_sys :: Oid */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_flush_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:268
-- pg_tin::tin_handler

CREATE FUNCTION tin_handler(internal) RETURNS index_am_handler
    PARALLEL SAFE IMMUTABLE STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'tin_handler_wrapper';
CREATE ACCESS METHOD tin TYPE INDEX HANDLER tin_handler;
COMMENT ON ACCESS METHOD tin IS 'tin: ctid two-level-bitmap full-text index';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:166
-- pg_tin::tin_highlight
CREATE  FUNCTION "tin_highlight"(
	"doc" TEXT, /* & str */
	"query" TEXT, /* & str */
	"start" TEXT DEFAULT '<b>', /* & str */
	"stop" TEXT DEFAULT '</b>' /* & str */
) RETURNS TEXT /* String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_highlight_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:72
-- pg_tin::tin_match
CREATE  FUNCTION "tin_match"(
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE COST 10
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/selectivity.rs:25
-- pg_tin::selectivity::tin_restrict

CREATE FUNCTION tin_restrict(internal, oid, internal, integer) RETURNS float8
    STABLE STRICT PARALLEL SAFE LANGUAGE c AS 'MODULE_PATHNAME', 'tin_restrict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:129
-- pg_tin::tin_score
CREATE  FUNCTION "tin_score"(
	"index" oid, /* pg_sys :: Oid */
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS double precision /* f64 */
STRICT STABLE PARALLEL SAFE COST 20
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:136
-- pg_tin::tin_score_inspect
CREATE  FUNCTION "tin_score_inspect"(
	"index" oid, /* pg_sys :: Oid */
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS jsonb /* pgrx :: JsonB */
STRICT STABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_score_inspect_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:119
-- pg_tin::tin_search_distance
CREATE  FUNCTION "tin_search_distance"(
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS double precision /* f64 */
STRICT STABLE PARALLEL SAFE COST 10
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_search_distance_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:111
-- pg_tin::tin_search_match
CREATE  FUNCTION "tin_search_match"(
	"doc" TEXT, /* & str */
	"query" TEXT /* & str */
) RETURNS bool /* bool */
STRICT STABLE PARALLEL SAFE COST 10
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_search_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:300
-- requires:
--   tin_match
--   tin_search_match
--   tin_search_distance
--   tin_handler
--   tin_restrict


CREATE OPERATOR ==> (
    LEFTARG = text,
    RIGHTARG = text,
    FUNCTION = tin_match,
    RESTRICT = tin_restrict,
    JOIN = contjoinsel
);
COMMENT ON OPERATOR ==> (text, text) IS 'full-text match: document ==> tin query';

CREATE OPERATOR ~> (
    LEFTARG = text,
    RIGHTARG = text,
    FUNCTION = tin_search_match,
    RESTRICT = tin_restrict,
    JOIN = contjoinsel
);
COMMENT ON OPERATOR ~> (text, text) IS 'search-box match: exact, prefix, fragment or typo';

CREATE OPERATOR <~> (
    LEFTARG = text,
    RIGHTARG = text,
    FUNCTION = tin_search_distance
);
COMMENT ON OPERATOR <~> (text, text) IS 'search-box rank: 0 exact, 1 prefix, 2 fragment, 3-4 typos';

CREATE OPERATOR CLASS text_tin_ops DEFAULT FOR TYPE text USING tin AS
    OPERATOR 1 ==> (text, text),
    OPERATOR 2 ~> (text, text),
    OPERATOR 3 <~> (text, text) FOR ORDER BY float_ops;
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:206
-- pg_tin::tin_segments
CREATE  FUNCTION "tin_segments"(
	"index" oid /* pg_sys :: Oid */
) RETURNS TABLE (
	"segment" INT,  /* i32 */
	"first_block" bigint,  /* i64 */
	"blocks" bigint,  /* i64 */
	"bytes" bigint,  /* i64 */
	"live_tuples" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_segments_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:255
-- pg_tin::tin_shared_stats
CREATE  FUNCTION "tin_shared_stats"() RETURNS TABLE (
	"segments" bigint,  /* i64 */
	"bytes" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_shared_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:179
-- pg_tin::tin_snippet
CREATE  FUNCTION "tin_snippet"(
	"doc" TEXT, /* & str */
	"query" TEXT, /* & str */
	"words" INT DEFAULT 30, /* i32 */
	"start" TEXT DEFAULT '<b>', /* & str */
	"stop" TEXT DEFAULT '</b>' /* & str */
) RETURNS TEXT /* String */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_snippet_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_tin/src/lib.rs:230
-- pg_tin::tin_stats
CREATE  FUNCTION "tin_stats"(
	"index" oid /* pg_sys :: Oid */
) RETURNS TABLE (
	"segments" INT,  /* i32 */
	"live_tuples" bigint,  /* i64 */
	"pending_tuples" bigint,  /* i64 */
	"pending_bytes" bigint,  /* i64 */
	"generation" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tin_stats_wrapper';
/* </end connected objects> */

