#!/usr/bin/env python3
"""Write an idempotent pg_tin upgrade script from the current install script.

    python3 scripts/upgrade-sql.py INSTALL.sql OLD NEW > crates/pg_tin/sql/pg_tin--OLD--NEW.sql

INSTALL.sql is the script `cargo pgrx schema` / `cargo pgrx install`
generates for version NEW. The upgrade brings any OLD install up to NEW,
however far back it was built (0.1.0 changed during development, so its
contents vary):

- every function is `CREATE OR REPLACE`d (with its SUPPORT, COST, ...);
  functions returning TABLE(...) are dropped first, because a changed
  column list can't be replaced in place (nothing depends on them);
- operators are created if missing, and `==>` / `~>` get their current
  estimators;
- operator-class members are added if missing;
- the access method and its handler are left alone (same C symbol).

Removed objects are not dropped: edit the output by hand for those.
"""
import re
import sys

install, old, new = sys.argv[1], sys.argv[2], sys.argv[3]
sql = open(install).read()

out = [
    f"-- pg_tin {old} -> {new}. Generated by scripts/upgrade-sql.py from the {new}",
    "-- install script; idempotent, so it also upgrades early development builds of",
    f"-- {old}. Run through ALTER EXTENSION pg_tin UPDATE.",
    "",
]

# Functions pgrx declares: CREATE  FUNCTION "name"( ... ) ... ; (up to the
# first line ending in ';' after AS). Hand-written ones: CREATE FUNCTION name(...
func_re = re.compile(r"^CREATE\s+FUNCTION\s+\"?(\w+)\"?\s*\((?:.|\n)*?;\n", re.M)
for m in func_re.finditer(sql):
    name, body = m.group(1), m.group(0)
    if name == "tin_handler":
        continue  # the access method's handler: unchanged C entry point
    returns_table = re.search(r"RETURNS\s+TABLE", body, re.I) is not None
    if returns_table:
        args = re.search(r"\((.*?)\)\s*RETURNS", body, re.S | re.I).group(1)
        types = []
        for a in re.sub(r"/\*.*?\*/", "", args).split(","):
            a = a.strip()
            if a:
                # "name" type [DEFAULT ...] -> type
                parts = a.replace('"', "").split()
                types.append(parts[1] if len(parts) > 1 else parts[0])
        out.append(f"DROP FUNCTION IF EXISTS {name}({', '.join(types)});")
    out.append(re.sub(r"^CREATE\s+FUNCTION", "CREATE OR REPLACE FUNCTION", body, flags=re.M))

ops = {
    "~>": "search-box match: exact, prefix, fragment or typo",
    "<~>": "search-box rank: 0 exact, 1 prefix, 2 fragment, 3-4 typos",
}
op_re = re.compile(r"^CREATE OPERATOR (\S+) \((?:.|\n)*?\);\n", re.M)
for m in op_re.finditer(sql):
    op, body = m.group(1), m.group(0)
    if op == "==>":
        # Present since 0.1.0's first build; its estimator came later.
        out.append("ALTER OPERATOR ==> (text, text) SET (RESTRICT = tin_restrict, JOIN = contjoinsel);\n")
        continue
    out.append(
        "DO $$ BEGIN\n"
        f"  IF NOT EXISTS (SELECT FROM pg_operator WHERE oprname = '{op}'\n"
        "                 AND oprleft = 'text'::regtype AND oprright = 'text'::regtype) THEN\n"
        + "".join("    " + l + "\n" for l in body.rstrip("\n").split("\n"))
        + "  END IF;\nEND $$;\n"
    )
    if op in ops:
        out.append(f"COMMENT ON OPERATOR {op} (text, text) IS '{ops[op]}';\n")

# Operator class members: add the strategies an early build lacks.
cls = re.search(r"CREATE OPERATOR CLASS (\w+) DEFAULT FOR TYPE text USING tin AS\n((?:.|\n)*?);\n", sql)
family = cls.group(1)
for line in cls.group(2).split("\n"):
    member = re.match(r"\s*OPERATOR (\d+) (.*?),?$", line)
    if not member:
        continue
    strategy, spec = member.group(1), member.group(2).strip()
    out.append(
        "DO $$ BEGIN\n"
        "  IF NOT EXISTS (SELECT FROM pg_amop o JOIN pg_opfamily f ON f.oid = o.amopfamily\n"
        f"                 WHERE f.opfname = '{family}' AND o.amopstrategy = {strategy}) THEN\n"
        f"    ALTER OPERATOR FAMILY {family} USING tin ADD OPERATOR {strategy} {spec};\n"
        "  END IF;\nEND $$;\n"
    )

print("\n".join(out))
